### ISSUE TITLE
Online zetten react website

### ISSUE THREAD

**Issue by JelleDelporte** [HOGENT-Web/frontendweb-budget#1]
Wanneer moet de website voor de opdracht front-end en webservices online staan? Moet deze vrijdag al online zijn bij het indienen van de opdracht of pas tijdens de examenperiode en voor hoe lang.

@Pieter-hogent @thomasaelbrecht

**Comment by Pieter-hogent** [comment]
In principe vanaf einde deadline tot en met je mondeling examen (dus vanaf 24 dec tot 2 feb), ergens daartussen gaan we jouw code en taak verbeteren en dan willen we het kunnen zien.

Als er een goede reden is waarom je het niet continue kan/wil hosten (je gebruikt één of andere service die betalend is na XX requests ofzo) is dat geen enkel probleem. Documenteer dat dan duidelijk in de README en zet erbij hoe we kunnen afspreken om alles live te zetten en het dus te zien.
